### ISSUE TITLE
이벤트를 통한 pop-up과 task-bar 컴포넌트 상호작용

### ISSUE THREAD

**Issue by unsnruu** [unsnruu/unsnruu.github.io#22]
구현된 redux의 전역상태관리 시스템을 이용해서 이벤트를 부착합니다.
이벤트를 통해 pop-up과 연관지어 task-bar가 특정 기능을 수행하도록 만들겠습니다.

## todos
- [x] close 이벤트 구현
- [x] open 이벤트 구현
- [x] minimize 이벤트 구현 : task-button을 클릭시에 다시 화면에서 나타나도록 설정하기
- [x] maximize 이벤트 구현
- [x] drag 이벤트 구현
- [x] resize 이벤트 구현
  - [x] border 스타일링을 제거하고 div를 통해서 설정한뒤 resize 이벤트를 부착하기
